### ISSUE TITLE
The game crashed while loading

### ISSUE THREAD

**Issue by sterh1275** [GetConfluxed/Biome-Specific-Dungeons#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  Enchantments Control Core (enchcontrol-1.12.2-1.1.2-0.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 3/9/19 9:50 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/darkhax/bookshelf/dataloader/sources/IDataProvider

	at net.darkhax.biomespecificdungeons.BiomeSpecificDungeons.<clinit>(BiomeSpecificDungeons.java:22)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Unknown Source)

	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)

	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)

	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Caused by: java.lang.ClassNotFoundException: net.darkhax.bookshelf.dataloader.sources.IDataProvider

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	... 40 more

Caused by: java.lang.NullPointerException

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.darkhax.biomespecificdungeons.BiomeSpecificDungeons.<clinit>(BiomeSpecificDungeons.java:22)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140308904 bytes (133 MB) / 356143104 bytes (339 MB) up to 791937024 bytes (755 MB)
	JVM Flags: 5 total; -Xmx768M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version        | Source                                 | Signature                                |
	|:----- |:--------------------- |:-------------- |:-------------------------------------- |:---------------------------------------- |
	| UC    | minecraft             | 1.12.2         | minecraft.jar                          | None                                     |
	| UC    | mcp                   | 9.42           | minecraft.jar                          | None                                     |
	| UC    | FML                   | 8.0.99.99      | forge-1.12.2-14.23.5.2775.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                 | 14.23.5.2775   | forge-1.12.2-14.23.5.2775.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | acorns                | 1.0            | acorns-ALPHA-0.1.jar                   | None                                     |
	| UC    | applepie              | 1.1            | applepie-1.1.jar                       | None                                     |
	| UC    | baubles               | 1.5.2          | Baubles-1.12-1.5.2.jar                 | None                                     |
	| UC    | baubleofundying       | 1.0.1          | BaubleOfUndying-1.12-1.0.1.jar         | None                                     |
	| UC    | betteradvancements    | 0.0.6.25       | BetterAdvancements-1.12.2-0.0.6.25.jar | None                                     |
	| UC    | betternether          | 0.1.5          | betternether-0.1.5-1.12.2.jar          | None                                     |
	| UC    | bettervillagers       | 1.12.2-0.2.0.0 | BetterVillagers-1.12.2-0.2.0.0.jar     | None                                     |
	| U     | biomespecificdungeons | 1.0.2          | BiomeSpecificDungeons-1.12.2-1.0.2.jar | None                                     |
	| U     | bullseye              | 3.0.7          | Bullseye-1.12.2-3.0.7.jar              | None                                     |
	| U     | burnbabyburn          | 1.1            | burnbabyburn-1.2.jar                   | None                                     |
	| U     | campfire              | 1.1            | campfire-1.12-v1.1.jar                 | None                                     |
	| U     | clearwater            | 1.0            | clearwater-1.0.jar                     | None                                     |
	| U     | controlledburn        | 1.12.2.008     | ControlledBurn-1.12.2.008.jar          | None                                     |
	| U     | coralreef             | 2.0            | CoralReef-2.5-1.12.2.jar               | None                                     |
	| U     | despawningspawners    | 1.1            | despawningspawners-1.12-1.2.0-2.jar    | None                                     |
	| U     | enchcontrol           | 1.1.2          | enchcontrol-1.12.2-1.1.2-0.jar         | None                                     |
	| U     | environmentalcreepers | 1.3.0          | environmentalcreepers-1.12.2-1.3.0.jar | None                                     |
	| U     | silentlib             | 3.0.10         | SilentLib-1.12.2-3.0.10-161.jar        | None                                     |
	| U     | extendeddays          | 0.2.9          | ExtendedDays-1.12.2-0.2.9-28.jar       | None                                     |
	| U     | fastleafdecay         | v14            | FastLeafDecay-v14.jar                  | None                                     |
	| U     | flour                 | 1.0.0          | flour-1.0.0.jar                        | None                                     |
	| U     | flowergirls           | 1.12.2-1.1.0   | flowergirls-1.12.2-1.1.0.jar           | None                                     |
	| U     | goldcauldron          | 1.1            | goldcauldron-1.1.jar                   | None                                     |
	| U     | gorofs                | 1.0            | gorofs-1.12.2-1.0.jar                  | None                                     |
	| U     | insomniac             | 1.3            | insomniac-1.3.jar                      | None                                     |
	| U     | jrftl                 | 1.1            | JRFTL[1.12.2]-1.1.jar                  | None                                     |
	| U     | jarm                  | 1.1.2          | Just+A+Raft+Mod-1.1.2.jar              | None                                     |
	| U     | milkspray             | 1.0.0          | milkspray-1.0.0.jar                    | None                                     |
	| U     | multithreadednoise    | 0.0.2          | MultithreadedNoise-1.12.2-0.0.2.jar    | None                                     |
	| U     | naturescompass        | 1.5.1          | NaturesCompass-1.12.2-1.5.1.jar        | None                                     |
	| U     | norecipebook          | 1.2.1          | noRecipeBook_v1.2.2formc1.12.2.jar     | None                                     |
	| U     | offlineskins          | 1.12.2-v4      | OfflineSkins-1.12.2-v4.jar             | None                                     |
	| U     | orecontrol            | 0.4.0          | orecontrol-1.12.0-0.4.0.jar            | None                                     |
	| U     | pcb                   | 1.5.0          | portablecraftbench-1.12.2-1.5.1.jar    | None                                     |
	| U     | practicalanvils       | 1.0-0a         | practicalanvils-1.0-0a.jar             | None                                     |
	| U     | puddles               | 1.1            | Puddles-1.1.jar                        | None                                     |
	| U     | recipemanipulator     | 1.0            | RecipeManipulator-1.12-0.3.1.13.jar    | None                                     |
	| U     | rmh                   | 1.0            | RemoveMouseoverHighlight-1.0.jar       | None                                     |
	| U     | resizable             | 0.0.1.0        | resizable-1.12.2-0.0.1.0.jar           | None                                     |
	| U     | scenter               | 1.12-3.11.0    | scenter-1.12.2-3.12.0.jar              | None                                     |
	| U     | simplifiedhorses      | 1.2            | SimplifiedHorses-v1.2-1.11-1.12.2.jar  | None                                     |
	| U     | peacefulskeletons     | 1.0            | Stone-Sworded-Skeletons-1.0.jar        | None                                     |
	| U     | storyoflife           | 0.0.1          | storyoflife-0.1.2.jar                  | None                                     |
	| U     | strawgolem            | 1.3            | strawgolem-1.3.jar                     | None                                     |
	| U     | venomousfangs         | 1.0            | VenomousFangs1.12-1.0.jar              | None                                     |
	| U     | wooltostring          | 1.12.2         | WoolToString-1.12.2-1.0.0.jar          | None                                     |
	| U     | zephmelt              | 1.2.2          | zephmelt-1.2.2.jar                     | None                                     |
	| U     | supertools            | 1.12.2-null    | VanillaPlusTools-1.2.jar               | None                                     |

	Loaded coremods (and transformers): 
offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  lain.mods.skins.asm.ASMTransformer
Enchantments Control Core (enchcontrol-1.12.2-1.1.2-0.jar)
  austeretony.enchcontrol.common.core.ECClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4653' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4653, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: VanillaFix.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz

**Comment by Darkhax** [comment]
Thanks for the report. The issue is that this mod requires the library mod [Bookshelf](https://minecraft.curseforge.com/projects/bookshelf/files/2683823). I forgot to include this information on the mod page and mod deps.
